apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-kubernetes
  description: A simple Hello World app for Kubernetes.
  tags:
    - nodejs
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=hello-kubernetes'
spec:
  type: Application
  lifecycle: Production
  owner: Jon

